pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        region = 'ap-south-1'
    }
    stages{
        stage('Checkout SCM'){
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/govindrao92/Terraform.git']])
                    
                }
                    
            }
        }
        stage('Initializing Terraform'){
            steps{
                dir('EKS'){
                    sh'terraform init'
                }
            }
        }
        stage('Formatting  Terraform code'){
            steps{
                dir('EKS'){
                    sh'terraform fmt'
                }
            }
        }
        stage('Validating Terraform'){
            steps{
                dir('EKS'){
                    sh'terraform validate'
                }
            }
        }
        stage('Previewing the infra using Terraform'){
            steps{
                dir('EKS'){
                    sh'terraform plan'
                }
            }
        }
    }
        
}
